##
## EPITECH PROJECT, 2022
## zappy
## File description:
## Makefile
##

all: clean build

build: fclean
	cp ./zappy_ai ../zappy_ai
	chmod +x ../zappy_ai

fclean:
	rm -f ../zappy_ai

clean:

.PHONY: all clean fclean re